apiVersion: v1
kind: Pod
metadata:
  name: network-issue
  labels:
    app: network-issue
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ping -w 10 non-existent-host"]
